hostname clh-hm90-3.msncj.mrsnet.cloud
log syslog informational
!
password <REDACTED>
enable password <REDACTED>
!
ip router-id 172.31.127.103
!
interface loopback0
 ip ospf area 0.0.0.3
 ip ospf passive
 ipv6 ospf6 area 0.0.0.3
 ipv6 ospf6 passive
!
interface loopback1
 ip ospf area 0.0.0.3
 ip ospf passive
 ipv6 ospf6 area 0.0.0.3
 ipv6 ospf6 passive
exit
!
interface vlan311
 ip ospf area 0.0.0.3
 ip ospf cost 3
 ipv6 ospf6 area 0.0.0.3
 ipv6 ospf6 cost 3
exit
!
interface vlan312
 ip ospf area 0.0.0.3
 ip ospf cost 4
 ipv6 ospf6 area 0.0.0.3
 ipv6 ospf6 cost 4
exit
!
router ospf
 ospf router-id 172.31.127.103
 area 0.0.0.3 stub no-summary
exit
!
router ospf6
 ospf router-id 172.31.127.103
 area 0.0.0.3 stub no-summary
exit
!
